services:
  app:
    build: .
    container_name: flowly
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flowly
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5173:5173"
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npx prisma generate && npm run dev:all"
  
  db:
    image: postgres:13-alpine
    container_name: flowly-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowly
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  node_modules: